import { Cpu, ShieldCheck } from 'lucide-react'
import type { EngineMode } from '@shared/types'

interface EngineBadgeProps {
  mode: EngineMode
  model: string | null
  compact?: boolean
}

/**
 * Always visible: the user should never have to guess whether an answer was
 * synthesised by a model or lifted verbatim by retrieval.
 */
export default function EngineBadge({ mode, model, compact = false }: EngineBadgeProps) {
  const isModel = mode === 'model'
  const Icon = isModel ? Cpu : ShieldCheck
  const label = isModel ? (model ?? 'Model') : 'Extractive mode'

  return (
    <span
      title={
        isModel
          ? 'Answers are generated by the configured model and every quote is verified against the transcript before display.'
          : 'No model provider configured — answers are verbatim retrieved passages, nothing is generated.'
      }
      className={`inline-flex items-center gap-1.5 rounded-full border font-semibold ${
        isModel ? 'border-ink/10 bg-ink text-white' : 'border-black/[0.08] bg-[#eef7d6] text-[#4f7a18]'
      } ${compact ? 'px-2.5 py-1 text-[10.5px]' : 'px-3 py-1.5 text-[11.5px]'}`}
    >
      <Icon size={compact ? 11 : 13} />
      {label}
    </span>
  )
}
